### ISSUE TITLE
Eliminate OldMessages

### ISSUE THREAD

**Issue by Torgen** [Torgen/codex-blackboard#66]
The efficiency issues with having a monolithic Messages collection were probably related to the observes that were running on it for paging, the bot, and server-side followups, combined with running the server in dev mode which caused it to restart, and changing the code during the hunt. Followups are client-side only now, and adding a timestamp restriction (with appropriate index) to the other two should achieve the same goal as archiving. We can also add a field to the Messages collection that says whether that message has been archived, either as a boolean or as a foreign key to the Page document the message was moved to, to allow loading only the most recent page.

**Comment by cscott** [comment]
I have to say, this is the change that makes me the most nervous about using your fork for a large codex team.  Historically, the meteor algorithms for updating clients and doing pub/sub notification of changes just didn't deal well with large collection sizes -- too many places did a linear pass over all rows in the db.  So, as you can tell, extreme measures were taken to ensure that any given meteor collection was relatively small, with only a single server thread doing the paging and moving old messages out of the most-frequently-loaded collection.

Looks like Meteor has beefed up its indexing, though, since the early days.  I hope the indexes cover all the interesting cases!

**Comment by Torgen** [comment]
I think the oplog driver supporting limit now (as long as a sort order is
set) is probably the bigger enabler of this.

**Comment by cscott** [comment]
Yeah, but we were an early adopter of the `oplog-<whatever>` branch that introduced this in meteor, and it wasn't sufficient at the time.  I suspect if things have improved it's more because as meteor has matured they've hunted down and eliminated all the weird corner cases that would still trigger full-collection scans on the margins.  It just takes a few missed cases to kill performance.

**Comment by Torgen** [comment]
If you have a mongodump of your database from last year, you can load it in
some version from [5a9b986,17d9d20) and it will move everything into the
single collection on first startup. I don't know if it's practical to do a
stress test so close to hunt.
Mongo's query optimizer doesn't always do what you expect. I changed the
separate {to: null} and $or: [{to:me},{from:me}] queries into a single
three way $or, and I expected it to do a three way merge with two queries
on [to, room_name, timestamp] and one on [from, room_name, timestamp], but
what it actually did was use the [room_name, timestamp] index only and just
drop the non matching messages. Intuitively that makes sense because there
are very few private messages, so the {from: me} almost entirely overlaps
the {to: null} and there aren't many {to: someone else} to drop, though I
don't know whether mongo keeps close enough track of the distribution in
the index to figure that out. I mention this because you didn't have the
[room_name, timestamp] index yet when you added the fixed paging, so maybe
that's the query that was causing the full collection scan.
